#Mysql属性配置文件,Spring-boot系统配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name : com.mysql.cj.jdbc.Driver
      url : jdbc:mysql://localhost:3306/mall_management_brand?autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      username : root
      password : root#root
  #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


