dubbo:
  scan:
    base-packages: com.yancey.smmall.management.thirdpartybrands.facade
  protocol:
    name: dubbo
    serialization: kryo
  registry:
    address: zookeeper://vm-centos:2181
    file: ./smmall/servers/log/dubbo-cache/${spring.application.name}/dubbo.cache
  provider:
    client: netty4
    retries: 0
    server: netty4
    group: smmall
    version: 1.0.0
    timeout: 10000
    dispatcher: message
  annotation:
    package: com.yancey.smmall.management.thirdpartybrands.facade
  consumer:
    client: netty4
    retries: 0
    group: smmall
    version: 1.0.0
    timeout: 10000
    check: false
