dubbo:
  protocol:
    name: dubbo
  registry:
    address: zookeeper://vm-centos:2181
    file: ./smmall/servers/log/dubbo-cache/${spring.application.name}/dubbo.cache
  consumer:
    client: netty4
    retries: 0
    group: smmall
    version: 1.0.0
    timeout: 10000
    check: false